Simplify notes
ietf-ivy-wg/network-inventory-yang pull request #55
Opened 2024-07-11 08:45 UTC by boucadair

see the general note at https://github.com/ietf-ivy-wg/network-inventory-yang/pull/54

2024-09-20 09:32 UTC, prmanna approved these changes

2024-09-30 18:15 UTC, italobusi requested changes

2024-09-30 18:15 UTC, italobusi commented on ietf-network-inventory.yang
> -    //information and remove this note
See my comment in #54: https://github.com/ietf-ivy-wg/network-inventory-yang/pull/54#discussion_r1781561314

2024-10-02 15:19 UTC, italobusi approved these changes

2024-10-02 15:28 UTC, italobusi commented on ietf-network-inventory.yang
> -    //information and remove this note
2024-10-01

The note to keep is the one above:

```
  // RFC Ed.: update the date below with the date of RFC publication
  // and remove this note.

```

2024-10-02 15:30 UTC, merged